local M = {}

local colors = require("wasabi.palette")

M.setup = function()
  return {
    -- NeoVim Default
    Normal = { fg = colors.fg, bg = colors.bg },
    NormalFloat = { fg = colors.fg, bg = colors.bg },
    Comment = { fg = colors.comment },
    Constant = { fg = colors.constant },
    String = { fg = colors.string },
    Character = { fg = colors.number },
    Number = { fg = colors.number },
    Boolean = { fg = colors.boolean },
    Float = { fg = colors.number },
    FloatBorder = { fg = colors.number },
    Operator = { fg = colors.operator },
    Keyword = { fg = colors.keyword },
    Keywords = { fg = colors.keyword },
    Identifier = { fg = colors.variable },
    Function = { fg = colors.Function },
    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.operator },
    Repeat = { fg = colors.operator },
    Label = { fg = colors.keyword },
    Exception = { fg = colors.keyword },
    PreProc = { fg = colors.keyword },
    Include = { fg = colors.keyword },
    Define = { fg = colors.keyword },
    Title = { fg = colors.string },
    Macro = { fg = colors.keyword },
    PreCondit = { fg = colors.keyword },
    Type = { fg = colors.Type },
    StorageClass = { fg = colors.keyword },
    Structure = { fg = colors.Type },
    TypeDef = { fg = colors.Type },
    Special = { fg = colors.keyword },
    SpecialComment = { fg = colors.comment },

    Error = { fg = colors.red },
    Todo = { fg = colors.black, bg = colors.orange },
    Underlined = { fg = colors.white, underline = true },
    EndOfBuffer = { fg = colors.linenr, bg = colors.end_bg },

    Cursor = { fg = colors.cursor },
    CursorLineNr = { fg = colors.cursorlinenr, bg = colors.end_bg },

    SignColumn = { bg = colors.end_bg },

    Conceal = { fg = colors.comment },
    CursorColumn = { bg = colors.black },
    CursorLine = { bg = colors.selection },
    ColorColumn = { bg = colors.selection },

    StatusLine = { fg = colors.statusline , bg = colors.black },
    StatusLineNC = { fg = colors.comment },
    StatusLineTerm = { fg = colors.white, bg = colors.black },
    StatusLineTermNC = { fg = colors.comment },

    Directory = { fg = colors.cyan },
    DiffAdd = { fg = colors.bg, bg = colors.number },
    DiffChange = { fg = colors.orange },
    DiffDelete = { fg = colors.red },
    DiffText = { fg = colors.comment },

    ErrorMsg = { fg = colors.bright_red },
    VertSplit = { fg = colors.black },
    WinSeparator = { fg = colors.black },
    Folded = { fg = colors.comment },
    FoldColumn = {},
    Search = { fg = colors.black, bg = colors.search },
    IncSearch = { fg = colors.comment },
    LineNr = { fg = colors.linenr, bg = colors.end_bg },
    MatchParen = { fg = colors.fg, underline = true },
    NonText = { fg = colors.nontext },
    Pmenu = { fg = colors.white, bg = colors.menubg },
    PmenuSel = { fg = colors.white, bg = colors.selection },
    PmenuSbar = { bg = colors.bg },
    PmenuThumb = { bg = colors.selection },

    Question = { fg = colors.magenta },
    QuickFixLine = { fg = colors.black, bg = colors.yellow },
    SpecialKey = { fg = colors.nontext },

    SpellBad = { fg = colors.spell, bg = colors.spell_bg, underline = true },
    SpellCap = { fg = colors.spell, bg = colors.spell_bg },
    SpellLocal = { fg = colors.spell, bg = colors.spell_bg },
    SpellRare = { fg = colors.spell, bg = colors.spell_bg },

    TabLine = { fg = colors.comment },
    TabLineSel = { fg = colors.white },
    TabLineFill = { bg = colors.bg },
    Terminal = { fg = colors.white, bg = colors.black },
    Visual = { bg = colors.visual },
    VisualNOS = { fg = colors.visual },
    WarningMsg = { fg = colors.yellow },
    WildMenu = { fg = colors.black, bg = colors.white },

    -- TreeSitter
    ["@error"] = { fg = colors.red },
    ["@punctuation.delimiter"] = { fg = colors.fg },
    ["@punctuation.bracket"] = { fg = colors.fg },
    ["@punctuation.special"] = { fg = colors.keyword },

    ["@constant"] = { fg = colors.constant },
    ["@constant.builtin"] = { fg = colors.constant },
    ["@symbol"] = { fg = colors.constant },

    ["@constant.macro"] = { fg = colors.constant },
    ["@string.regex"] = { fg = colors.string },
    ["@string"] = { fg = colors.string },
    ["@string.escape"] = { fg = colors.string },
    ["@character"] = { fg = colors.number },
    ["@number"] = { fg = colors.number },
    ["@boolean"] = { fg = colors.boolean },
    ["@float"] = { fg = colors.number },
    ["@annotation"] = { fg = colors.keyword },
    ["@attribute"] = { fg = colors.keyword },
    ["@namespace"] = { fg = colors.keyword },

    ["@function.builtin"] = { fg = colors.Function },
    ["@function"] = { fg = colors.Function },
    ["@function.macro"] = { fg = colors.Function },
    ["@parameter"] = { fg = colors.variable },
    ["@parameter.reference"] = { fg = colors.variable },
    ["@method"] = { fg = colors.Function },
    ["@field"] = { fg = colors.variable },
    ["@property"] = { fg = colors.variable },
    ["@constructor"] = { fg = colors.Type },

    ["@conditional"] = { fg = colors.operator },
    ["@repeat"] = { fg = colors.operator },
    ["@label"] = { fg = colors.keyword },

    ["@keyword"] = { fg = colors.keyword },
    ["@keyword.function"] = { fg = colors.keyword },
    ["@keyword.function.ruby"] = { fg = colors.keyword },
    ["@keyword.operator"] = { fg = colors.operator },
    ["@operator"] = { fg = colors.operator },
    ["@exception"] = { fg = colors.keyword },
    ["@type"] = { fg = colors.Type },
    ["@type.builtin"] = { fg = colors.Type },
    ["@type.qualifier"] = { fg = colors.keyword },
    ["@structure"] = { fg = colors.Type },
    ["@include"] = { fg = colors.keyword },
    ["@keyword.import"] = { fg = colors.keyword },

    ["@variable"] = { fg = colors.variable },
    ["@variable.builtin"] = { fg = colors.variable },

    ["@text"] = { fg = colors.fg },
    ["@text.strong"] = { fg = colors.fg, bold = true }, -- bold
    ["@text.emphasis"] = { fg = colors.fg, italic = true }, -- italic
    ["@text.underline"] = { fg = colors.fg, underline = true },
    ["@text.title"] = { fg = colors.string, bold = true }, -- title
    ["@text.literal"] = { fg = colors.string }, -- inline code
    ["@text.uri"] = { fg = colors.string, italic = true }, -- urls
    ["@text.reference"] = { fg = colors.constant, bold = true },

    ["@tag"] = { fg = colors.keyword },
    ["@tag.attribute"] = { fg = colors.keyword },
    ["@tag.delimiter"] = { fg = colors.operator },

    -- Semantic
    ["@class"] = { fg = colors.Type },
    ["@struct"] = { fg = colors.Type },
    ["@enum"] = { fg = colors.Type },
    ["@enumMember"] = { fg = colors.constant },
    ["@event"] = { fg = colors.keyword },
    ["@interface"] = { fg = colors.Type },
    ["@modifier"] = { fg = colors.keyword },
    ["@regexp"] = { fg = colors.string },
    ["@typeParameter"] = { fg = colors.Type },
    ["@decorator"] = { fg = colors.keyword },

    -- LSP Semantic (0.9+)
    ["@lsp.type.class"] = { fg = colors.Type },
    ["@lsp.type.enum"] = { fg = colors.Type },
    ["@lsp.type.decorator"] = { fg = colors.keyword },
    ["@lsp.type.enumMember"] = { fg = colors.constant },
    ["@lsp.type.function"] = { fg = colors.Function },
    ["@lsp.type.interface"] = { fg = colors.Type },
    ["@lsp.type.macro"] = { fg = colors.keyword },
    ["@lsp.type.method"] = { fg = colors.Function },
    ["@lsp.type.namespace"] = { fg = colors.keyword },
    ["@lsp.type.parameter"] = { fg = colors.variable },
    ["@lsp.type.property"] = { fg = colors.variable },
    ["@lsp.type.struct"] = { fg = colors.Type },
    ["@lsp.type.type"] = { fg = colors.Type },
    ["@lsp.type.variable"] = { fg = colors.variable },

    -- HTML
    htmlArg = { fg = colors.variable },
    htmlBold = { fg = colors.string, bold = true },
    htmlEndTag = { fg = colors.keyword },
    htmlH1 = { fg = colors.string },
    htmlH2 = { fg = colors.string },
    htmlH3 = { fg = colors.string },
    htmlH4 = { fg = colors.string },
    htmlH5 = { fg = colors.string },
    htmlH6 = { fg = colors.string },
    htmlItalic = { fg = colors.string, italic = true },
    htmlLink = { fg = colors.string, underline = true },
    htmlSpecialChar = { fg = colors.string },
    htmlSpecialTagName = { fg = colors.keyword },
    htmlString = { fg = colors.fg },
    htmlTag = { fg = colors.keyword },
    htmlTagN = { fg = colors.keyword },
    htmlTagName = { fg = colors.keyword },
    htmlTitle = { fg = colors.string },

    -- Markdown
    markdownBlockquote = { fg = colors.yellow, italic = true },
    markdownBold = { fg = colors.orange, bold = true },
    markdownCode = { fg = colors.orange },
    markdownCodeBlock = { fg = colors.orange },
    markdownCodeDelimiter = { fg = colors.red },
    markdownH1 = { fg = colors.blue, bold = true },
    markdownH2 = { fg = colors.blue, bold = true },
    markdownH3 = { fg = colors.blue, bold = true },
    markdownH4 = { fg = colors.blue, bold = true },
    markdownH5 = { fg = colors.blue, bold = true },
    markdownH6 = { fg = colors.blue, bold = true },
    markdownHeadingDelimiter = { fg = colors.red },
    markdownHeadingRule = { fg = colors.comment },
    markdownId = { fg = colors.magenta },
    markdownIdDeclaration = { fg = colors.cyan },
    markdownIdDelimiter = { fg = colors.magenta },
    markdownItalic = { fg = colors.yellow, italic = true },
    markdownLinkDelimiter = { fg = colors.magenta },
    markdownLinkText = { fg = colors.blue },
    markdownListMarker = { fg = colors.cyan },
    markdownOrderedListMarker = { fg = colors.red },
    markdownRule = { fg = colors.comment },

    --  Diff
    diffAdded = { fg = colors.orange },
    diffRemoved = { fg = colors.red },
    diffFileId = { fg = colors.yellow, bold = true, reverse = true },
    diffFile = { fg = colors.nontext },
    diffNewFile = { fg = colors.orange },
    diffOldFile = { fg = colors.red },

    debugPc = { bg = colors.menu },
    debugBreakpoint = { fg = colors.red, reverse = true },

    -- Git Signs
    GitSignsAdd = { fg = colors.number },
    GitSignsChange = { fg = colors.orange },
    GitSignsDelete = { fg = colors.bright_red },
    GitSignsAddLn = { fg = colors.black, bg = colors.number },
    GitSignsChangeLn = { fg = colors.black, bg = colors.orange },
    GitSignsDeleteLn = { fg = colors.black, bg = colors.bright_red },
    GitSignsCurrentLineBlame = { fg = colors.white },

    -- NvimTree
    NvimTreeNormal = { fg = colors.fg, bg = colors.menu },
    NvimTreeVertSplit = { fg = colors.bg, bg = colors.bg },
    NvimTreeRootFolder = { fg = colors.fg, bold = true },
    NvimTreeGitDirty = { fg = colors.yellow },
    NvimTreeGitNew = { fg = colors.number },
    NvimTreeImageFile = { fg = colors.blue },
    NvimTreeFolderIcon = { fg = colors.magenta },
    NvimTreeIndentMarker = { fg = colors.nontext },
    NvimTreeEmptyFolderName = { fg = colors.comment },
    NvimTreeFolderName = { fg = colors.fg },
    NvimTreeSpecialFile = { fg = colors.blue, underline = true },
    NvimTreeOpenedFolderName = { fg = colors.fg },
    NvimTreeCursorLine = { bg = colors.selection },
    NvimTreeIn = { bg = colors.selection },

    -- LSP
    --DiagnosticError = { fg = colors.red },
    --DiagnosticWarn = { fg = colors.yellow },
    --DiagnosticInfo = { fg = colors.cyan },
    --DiagnosticHint = { fg = colors.cyan },
    --DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
    --DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    --DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
    --DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
    --DiagnosticSignError = { fg = colors.red },
    --DiagnosticSignWarn = { fg = colors.yellow },
    --DiagnosticSignInfo = { fg = colors.cyan },
    --DiagnosticSignHint = { fg = colors.cyan },
    --DiagnosticFloatingError = { fg = colors.red },
    --DiagnosticFloatingWarn = { fg = colors.yellow },
    --DiagnosticFloatingInfo = { fg = colors.cyan },
    --DiagnosticFloatingHint = { fg = colors.cyan },
    --DiagnosticVirtualTextError = { fg = colors.red },
    --DiagnosticVirtualTextWarn = { fg = colors.yellow },
    --DiagnosticVirtualTextInfo = { fg = colors.cyan },
    --DiagnosticVirtualTextHint = { fg = colors.cyan },

    --LspDiagnosticsDefaultError = { fg = colors.red },
    --LspDiagnosticsDefaultWarning = { fg = colors.yellow },
    --LspDiagnosticsDefaultInformation = { fg = colors.cyan },
    --LspDiagnosticsDefaultHint = { fg = colors.cyan },
    --LspDiagnosticsUnderlineError = { fg = colors.red, undercurl = true },
    --LspDiagnosticsUnderlineWarning = { fg = colors.yellow, undercurl = true },
    --LspDiagnosticsUnderlineInformation = { fg = colors.cyan, undercurl = true },
    --LspDiagnosticsUnderlineHint = { fg = colors.cyan, undercurl = true },
    --LspReferenceText = { fg = colors.yellow, bg = colors.selection },
    --LspReferenceRead = { fg = colors.yellow, bg = colors.selection },
    --LspReferenceWrite = { fg = colors.yellow, bg = colors.selection },
    --LspCodeLens = { fg = colors.cyan },

    -- Cmp
    --CmpItemAbbr = { fg = colors.white, bg = colors.bg },
    --CmpItemKind = { fg = colors.white, bg = colors.bg },
    --CmpItemKindMethod = { link = "@method" },
    --CmpItemKindText = { link = "@text" },
    --CmpItemKindFunction = { link = "@function" },
    --CmpItemKindConstructor = { link = "@type" },
    --CmpItemKindVariable = { link = "@variable" },
    --CmpItemKindClass = { link = "@type" },
    --CmpItemKindInterface = { link = "@type" },
    --CmpItemKindModule = { link = "@namespace" },
    --CmpItemKindProperty = { link = "@property" },
    --CmpItemKindOperator = { link = "@operator" },
    --CmpItemKindReference = { link = "@parameter.reference" },
    --CmpItemKindUnit = { link = "@field" },
    --CmpItemKindValue = { link = "@field" },
    --CmpItemKindField = { link = "@field" },
    --CmpItemKindEnum = { link = "@field" },
    --CmpItemKindKeyword = { link = "@keyword" },
    --CmpItemKindSnippet = { link = "@text" },
    --CmpItemKindEvent = { link = "@constant" },
    --CmpItemKindEnumMember = { link = "@field" },
    --CmpItemKindConstant = { link = "@constant" },
    --CmpItemKindStruct = { link = "@structure" },
    --CmpItemKindTypeParameter = { link = "@parameter" },

    -- WinPicker
    --WinPicker = { fg = colors.bg, bg = colors.number },

    -- indent-blankline.nvim
    IblIndent = { fg = colors.cursorline },
    IblScope  = { fg = colors.cursorline },
  }
end

return M
