local M = {}

local colors = require("wasabi.palette")

M.setup = function()
  return {
    -- NeoVim Default
    Normal = { fg = colors.fg, bg = colors.bg },
    NormalFloat = { fg = colors.fg, bg = colors.bg },
    Comment = { fg = colors.comment },
    Constant = { fg = colors.constant },
    String = { fg = colors.string },
    Character = { fg = colors.number },
    Number = { fg = colors.number },
    Boolean = { fg = colors.boolean },
    Float = { fg = colors.number },
    FloatBorder = { fg = colors.number },
    Operator = { fg = colors.operator },
    Keyword = { fg = colors.keyword },
    Keywords = { fg = colors.keyword },
    Identifier = { fg = colors.variable },
    Function = { fg = colors.Function },
    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.operator },
    Repeat = { fg = colors.operator },
    Label = { fg = colors.keyword },
    Exception = { fg = colors.keyword },
    PreProc = { fg = colors.keyword },
    Include = { fg = colors.keyword },
    Define = { fg = colors.keyword },
    Title = { fg = colors.string },
    Macro = { fg = colors.keyword },
    PreCondit = { fg = colors.keyword },
    Type = { fg = colors.Type },
    StorageClass = { fg = colors.keyword },
    Structure = { fg = colors.Type },
    TypeDef = { fg = colors.Type },
    Special = { fg = colors.keyword },
    SpecialComment = { fg = colors.comment },

    Error = { fg = colors.red },
    Todo = { fg = colors.black, bg = colors.orange },
    Underlined = { fg = colors.white, underline = true },
    EndOfBuffer = { fg = colors.linenr, bg = colors.gray_9 },

    Cursor = { fg = colors.cursor },
    CursorLineNr = { fg = colors.cursorlinenr, bg = colors.gray_9 },

    SignColumn = { bg = colors.gray_9 },

    Conceal = { fg = colors.comment },
    CursorColumn = { bg = colors.black },
    CursorLine = { bg = colors.selection },
    ColorColumn = { bg = colors.selection },

    StatusLine = { fg = colors.statusline , bg = colors.black },
    StatusLineNC = { fg = colors.comment },
    StatusLineTerm = { fg = colors.white, bg = colors.black },
    StatusLineTermNC = { fg = colors.comment },

    Directory = { fg = colors.cyan },
    DiffAdd = { fg = colors.bg, bg = colors.number },
    DiffChange = { fg = colors.orange },
    DiffDelete = { fg = colors.red },
    DiffText = { fg = colors.comment },

    ErrorMsg = { fg = colors.bright_red },
    VertSplit = { fg = colors.black },
    WinSeparator = { fg = colors.black },
    Folded = { fg = colors.comment },
    FoldColumn = {},
    Search = { fg = colors.black, bg = colors.search },
    IncSearch = { fg = colors.comment },
    LineNr = { fg = colors.linenr, bg = colors.gray_9 },
    MatchParen = { fg = colors.fg, underline = true },
    NonText = { fg = colors.nontext },
    Pmenu = { fg = colors.white, bg = colors.menubg },
    PmenuSel = { fg = colors.white, bg = colors.selection },
    PmenuSbar = { bg = colors.bg },
    PmenuThumb = { bg = colors.selection },

    Question = { fg = colors.magenta },
    QuickFixLine = { fg = colors.black, bg = colors.yellow },
    SpecialKey = { fg = colors.nontext },

    SpellBad = { fg = colors.spell, bg = colors.spell_bg, underline = true },
    SpellCap = { fg = colors.spell, bg = colors.spell_bg },
    SpellLocal = { fg = colors.spell, bg = colors.spell_bg },
    SpellRare = { fg = colors.spell, bg = colors.spell_bg },

    TabLine = { fg = colors.fg, bg = colors.tabline },
    TabLineSel = { fg = colors.fg, bg = colors.tabline_sel },
    TabLineFill = { bg = colors.fg, bg = colors.tabline_fill },

    Terminal = { fg = colors.white, bg = colors.black },
    Visual = { bg = colors.visual },
    VisualNOS = { fg = colors.visual },
    WarningMsg = { fg = colors.yellow },
    WildMenu = { fg = colors.black, bg = colors.white },

    -- TreeSitter
    ["@error"] = { fg = colors.red },
    ["@punctuation.delimiter"] = { fg = colors.fg },
    ["@punctuation.bracket"] = { fg = colors.fg },
    ["@punctuation.special"] = { fg = colors.keyword },

    ["@constant"] = { fg = colors.constant },
    ["@constant.builtin"] = { fg = colors.constant },
    ["@symbol"] = { fg = colors.constant },

    ["@constant.macro"] = { fg = colors.constant },
    ["@string.regex"] = { fg = colors.string },
    ["@string"] = { fg = colors.string },
    ["@string.escape"] = { fg = colors.string },
    ["@character"] = { fg = colors.number },
    ["@number"] = { fg = colors.number },
    ["@boolean"] = { fg = colors.boolean },
    ["@float"] = { fg = colors.number },
    ["@annotation"] = { fg = colors.keyword },
    ["@attribute"] = { fg = colors.keyword },
    ["@namespace"] = { fg = colors.keyword },

    ["@function.builtin"] = { fg = colors.Function },
    ["@function"] = { fg = colors.Function },
    ["@function.macro"] = { fg = colors.Function },
    ["@parameter"] = { fg = colors.variable },
    ["@parameter.reference"] = { fg = colors.variable },
    ["@method"] = { fg = colors.Function },
    ["@field"] = { fg = colors.variable },
    ["@property"] = { fg = colors.variable },
    ["@constructor"] = { fg = colors.Type },

    ["@conditional"] = { fg = colors.operator },
    ["@repeat"] = { fg = colors.operator },
    ["@label"] = { fg = colors.keyword },

    ["@keyword"] = { fg = colors.keyword },
    ["@keyword.function"] = { fg = colors.keyword },
    ["@keyword.function.ruby"] = { fg = colors.keyword },
    ["@keyword.operator"] = { fg = colors.operator },
    ["@operator"] = { fg = colors.operator },
    ["@exception"] = { fg = colors.keyword },
    ["@type"] = { fg = colors.Type },
    ["@type.builtin"] = { fg = colors.Type },
    ["@type.qualifier"] = { fg = colors.keyword },
    ["@structure"] = { fg = colors.Type },
    ["@include"] = { fg = colors.keyword },
    ["@keyword.import"] = { fg = colors.keyword },

    ["@variable"] = { fg = colors.variable },
    ["@variable.builtin"] = { fg = colors.variable },

    ["@text"] = { fg = colors.fg },
    ["@text.strong"] = { fg = colors.fg, bold = true }, -- bold
    ["@text.emphasis"] = { fg = colors.fg, italic = true }, -- italic
    ["@text.underline"] = { fg = colors.fg, underline = true },
    ["@text.title"] = { fg = colors.string, bold = true }, -- title
    ["@text.literal"] = { fg = colors.gray_5 }, -- inline code
    ["@markup.raw"] = { fg = colors.gray_5 }, -- inline code (new capture)
    ["@markup.raw.block"] = { fg = colors.gray_5 }, -- code blocks
    ["@punctuation.special.markdown"] = { fg = colors.gray_5 }, -- table borders
    ["@text.uri"] = { fg = colors.string, italic = true }, -- urls
    ["@text.reference"] = { fg = colors.constant, bold = true },

    ["@tag"] = { fg = colors.keyword },
    ["@tag.attribute"] = { fg = colors.keyword },
    ["@tag.delimiter"] = { fg = colors.operator },

    -- Semantic
    ["@class"] = { fg = colors.Type },
    ["@struct"] = { fg = colors.Type },
    ["@enum"] = { fg = colors.Type },
    ["@enumMember"] = { fg = colors.constant },
    ["@event"] = { fg = colors.keyword },
    ["@interface"] = { fg = colors.Type },
    ["@modifier"] = { fg = colors.keyword },
    ["@regexp"] = { fg = colors.string },
    ["@typeParameter"] = { fg = colors.Type },
    ["@decorator"] = { fg = colors.keyword },

    -- LSP Semantic (0.9+)
    ["@lsp.type.class"] = { fg = colors.Type },
    ["@lsp.type.enum"] = { fg = colors.Type },
    ["@lsp.type.decorator"] = { fg = colors.keyword },
    ["@lsp.type.enumMember"] = { fg = colors.constant },
    ["@lsp.type.function"] = { fg = colors.Function },
    ["@lsp.type.interface"] = { fg = colors.Type },
    ["@lsp.type.macro"] = { fg = colors.keyword },
    ["@lsp.type.method"] = { fg = colors.Function },
    ["@lsp.type.namespace"] = { fg = colors.keyword },
    ["@lsp.type.parameter"] = { fg = colors.variable },
    ["@lsp.type.property"] = { fg = colors.variable },
    ["@lsp.type.struct"] = { fg = colors.Type },
    ["@lsp.type.type"] = { fg = colors.Type },
    ["@lsp.type.variable"] = { fg = colors.variable },

    -- HTML
    htmlArg = { fg = colors.variable },
    htmlBold = { fg = colors.string, bold = true },
    htmlEndTag = { fg = colors.keyword },
    htmlH1 = { fg = colors.string },
    htmlH2 = { fg = colors.string },
    htmlH3 = { fg = colors.string },
    htmlH4 = { fg = colors.string },
    htmlH5 = { fg = colors.string },
    htmlH6 = { fg = colors.string },
    htmlItalic = { fg = colors.string, italic = true },
    htmlLink = { fg = colors.string, underline = true },
    htmlSpecialChar = { fg = colors.string },
    htmlSpecialTagName = { fg = colors.keyword },
    htmlString = { fg = colors.fg },
    htmlTag = { fg = colors.keyword },
    htmlTagN = { fg = colors.keyword },
    htmlTagName = { fg = colors.keyword },
    htmlTitle = { fg = colors.string },

    -- Markdown
    markdownBlockquote = { fg = colors.yellow, italic = true },
    markdownBold = { fg = colors.fg, bg = colors.bright_gray, bold = true },
    markdownCode = { fg = colors.bright_yellow, bg = colors.cursorline },
    markdownCodeBlock = { fg = colors.orange },
    markdownCodeDelimiter = { fg = colors.red },
    markdownH1 = { fg = colors.green, bold = true },
    markdownH2 = { fg = colors.green, bold = true },
    markdownH3 = { fg = colors.green, bold = true },
    markdownH4 = { fg = colors.green, bold = true },
    markdownH5 = { fg = colors.green, bold = true },
    markdownH6 = { fg = colors.green, bold = true },
    markdownHeadingDelimiter = { fg = colors.red },
    markdownHeadingRule = { fg = colors.comment },
    markdownId = { fg = colors.magenta },
    markdownIdDeclaration = { fg = colors.cyan },
    markdownIdDelimiter = { fg = colors.magenta },
    markdownItalic = { fg = colors.yellow, italic = true },
    markdownLinkDelimiter = { fg = colors.magenta },
    markdownLinkText = { fg = colors.fg, underline = true },
    markdownListMarker = { fg = colors.cyan },
    markdownOrderedListMarker = { fg = colors.red },
    markdownRule = { fg = colors.comment },

    -- render-markdown.nvim
    RenderMarkdownH1 = { fg = colors.green, bold = true },
    RenderMarkdownH2 = { fg = colors.green, bold = true },
    RenderMarkdownH3 = { fg = colors.green, bold = true },
    RenderMarkdownH4 = { fg = colors.green, bold = true },
    RenderMarkdownH5 = { fg = colors.green, bold = true },
    RenderMarkdownH6 = { fg = colors.green, bold = true },
    RenderMarkdownH1Bg = { fg = colors.green, bold = true },
    RenderMarkdownH2Bg = { fg = colors.green, bold = true },
    RenderMarkdownH3Bg = { fg = colors.green, bold = true },
    RenderMarkdownH4Bg = { fg = colors.green, bold = true },
    RenderMarkdownH5Bg = { fg = colors.green, bold = true },
    RenderMarkdownH6Bg = { fg = colors.green, bold = true },
    RenderMarkdownLink = { fg = colors.fg, underline = true },
    RenderMarkdownBold = { fg = colors.fg, bg = colors.bright_gray, bold = true },
    RenderMarkdownNormal = { fg = colors.fg },
    RenderMarkdownCode = { fg = colors.bright_yellow, bg = colors.cursorline },
    RenderMarkdownCodeInline = { fg = colors.bright_yellow, bg = colors.cursorline },

    --  Diff
    diffAdded = { fg = colors.orange },
    diffRemoved = { fg = colors.red },
    diffFileId = { fg = colors.yellow, bold = true, reverse = true },
    diffFile = { fg = colors.nontext },
    diffNewFile = { fg = colors.orange },
    diffOldFile = { fg = colors.red },

    -- Git Signs
    GitSignsAdd = { fg = colors.number },
    GitSignsChange = { fg = colors.orange },
    GitSignsDelete = { fg = colors.bright_red },
    GitSignsAddLn = { fg = colors.black, bg = colors.number },
    GitSignsChangeLn = { fg = colors.black, bg = colors.orange },
    GitSignsDeleteLn = { fg = colors.black, bg = colors.bright_red },
    GitSignsCurrentLineBlame = { fg = colors.white },

    -- NvimTree
    NvimTreeNormal = { fg = colors.fg },
    NvimTreeEndOfBuffer = { fg = colors.bg, bg = colors.bg },
    NvimTreeVertSplit = { fg = colors.fg },
    NvimTreeRootFolder = { fg = colors.bright_blue },
    NvimTreeGitDirty = { fg = colors.bright_blue },
    NvimTreeGitNew = { fg = colors.bright_blue },
    NvimTreeImageFile = { fg = colors.fg },
    NvimTreeFolderIcon = { fg = colors.bright_blue },
    NvimTreeIndentMarker = { fg = colors.fg },
    NvimTreeEmptyFolderName = { fg = colors.bright_blue },
    NvimTreeFolderName = { fg = colors.bright_blue },
    NvimTreeSpecialFile = { fg = colors.fg },
    NvimTreeOpenedFolderName = { fg = colors.bright_blue },
    NvimTreeCursorLine = { bg = colors.gray_9 },
    NvimTreeIn = { fg = colors.fg },
    NvimTreeOpenedFile = { fg = colors.bright_yellow },
    NvimTreeGitFileDirtyHL = { fg = colors.fg },
    NvimTreeGitFileNewHL = { fg = colors.fg },
    NvimTreeGitFileMergeHL = { fg = colors.fg },
    NvimTreeGitFileRenamedHL = { fg = colors.fg },
    NvimTreeGitFileStagedHL = { fg = colors.fg },
    NvimTreeGitFileDeletedHL = { fg = colors.fg },
    NvimTreeGitFileIgnoredHL = { fg = colors.fg },
    NvimTreeGitFolderDirtyHL = { fg = colors.bright_blue },
    NvimTreeGitFolderNewHL = { fg = colors.bright_blue },
    NvimTreeGitFolderMergeHL = { fg = colors.bright_blue },
    NvimTreeGitFolderRenamedHL = { fg = colors.bright_blue },
    NvimTreeGitFolderStagedHL = { fg = colors.bright_blue },
    NvimTreeGitFolderDeletedHL = { fg = colors.bright_blue },
    NvimTreeGitFolderIgnoredHL = { fg = colors.bright_blue },
    NvimTreeSymlink = { fg = colors.fg },
    NvimTreeSymlinkFolderName = { fg = colors.bright_blue },
    NvimTreeSymlinkIcon = { fg = colors.bright_blue },
    NvimTreeExecFile = { fg = colors.fg },
    NvimTreeSocket = { fg = colors.fg },
    NvimTreePipe = { fg = colors.fg },

    -- indent-blankline.nvim
    IblIndent = { fg = colors.cursorline },
    IblScope  = { fg = colors.cursorline },
  }
end

return M
